### ISSUE TITLE
finish point #1

### ISSUE THREAD

**Issue by sreynolds2** [mcolvin/PSPAP-Reboot#17]
@mcolvin  In line 45 of 2017-06-30-Initial-Densities.Rmd the point drops off without being finished, and I wasn't quite sure I knew  what work you were going for there.  Did you mean densities?   

![image](https://user-images.githubusercontent.com/27437647/26952759-73b2fae2-4c6c-11e7-9c1c-4feb46b89187.png)

**Comment by mcolvin** [comment]
I think I was going towards distribution but then decided not to as we are
not really hitting it yet.

**Comment by sreynolds2** [comment]
Fixed with "small wording update" commit.
